<?php

/**
 * @file
 *   This module is used to create apikey for site and create a Url that will respond JSON Representation of Node based
 * on SiteApiKey.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */

function axelerant_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'system_site_information_settings') {
    $form['actions']['submit']['#value'] = t('Update Configuration');

    $form['siteapikey'] = [
      '#type' => 'textfield',
      '#title' => t('Site API Key'),
      '#default_value' => \Drupal::config('site_api_key.settings')->get('siteapikey'),
    ];

    foreach (array_keys($form['actions']) as $action) {
      if ($form['actions'][$action]['#type'] == 'submit') {
        $form['actions'][$action]['#submit'][] = 'site_api_key_submit';
      }
    }
  }
}

/*
 * Form Submit call back.
 */
function site_api_key_submit(&$form, FormStateInterface $form_state) {
  $site_api_key =  $form_state->getValue('siteapikey');
  $config = \Drupal::service('config.factory')->getEditable('site_api_key.settings');
  $config->set('siteapikey', $site_api_key)->save();
  drupal_set_message(t('The Site API key has been saved with @api_key value', ['@api_key' => $site_api_key]), 'status');
}
